---
dir_dot_files_src: /vagrant/zzz/vmSetup/config/dotFiles
dir_home: /home/vagrant
files_dot_files:
  - ".alias"
  - ".ansible.cfg"
  - ".bash_aliases"
  - ".bash_profile"
  - ".bashrc"
  - ".env"
  - ".profile"
  - ".rspec"
  - ".tmux.conf"
  - ".vimrc"