---
- name: Delete the dot files.
  file:
    path: "{{dir_home}}/{{item}}"
    state: absent
  with_items: "{{files_dot_files}}"

- name: Symlink config files.
  file:
    src: "{{dir_dot_files_src}}/{{item}}"
    dest: "{{dir_home}}/{{item}}"
    state: link
  with_items: "{{files_dot_files}}"